# Generated by Django 5.1.2 on 2024-10-12 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="catchphrase",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="class_name",
            field=models.CharField(db_column="class", max_length=255),
        ),
    ]
