# Generated by Django 5.1.2 on 2024-10-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_person_catchphrase_alter_person_class_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="class_name",
            field=models.CharField(max_length=255),
        ),
    ]
